version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "rossyman"
    reviewers:
      - "rossyman"
    commit-message:
      prefix: "JSMNM-D"
      include: "scope"
    target_branch: "develop"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "rossyman"
    reviewers:
      - "rossyman"
    commit-message:
      prefix: "JSMNM-D"
      include: "scope"
    target_branch: "develop"
